backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'yachts'
    label: 'Yachts'
    folder: 'content/yachts'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{name}}/index'
    editor:
      preview: false
    fields:
      - { label: 'URL', name: 'slug', widget: 'string', required: true, regex: ['^[a-zA-Z0-9_-]*$', 'Alphanumeric characters, hyphens, and underscores only.']}
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Details', name: 'details', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Length", name: "length", widget: "number", value_type: "int" }
      - { label: "Guests", name: "guests", widget: "number", value_type: "int" }
      - { label: "Cabins", name: "cabins", widget: "number", value_type: "int" }
      - { label: "Crew", name: "crew", widget: "number", value_type: "int" }
      - { label: 'Price description', name: 'price', widget: 'markdown' }