backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'yachts'
    label: 'Yachts'
    folder: 'content/yachts'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{name}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }